name: Dispatch Workflow
description: Dispatches a workflow in another Repository

inputs:
  token:
    description: 'GitHub Auth Token'
    required: true
  repo:
    description: 'The repository to dispatch the workflow in - i.e. owner/repo'
    required: true
  workflow_id:
    description: 'The ID of the workflow to dispatch - i.e. partial-build.yml'
    required: true
  ref:
    description: 'The branch to dispatch the workflow on - i.e. main'
    required: false
    default: 'main'
  inputs:
    description: 'The inputs to pass to the workflow - i.e. {"package_name":"partial-build.yml"}'
    required: false
    default: '{}'

runs:
  using: "composite"
  steps:
    - run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          $GITHUB_API_URL/repos/${{ inputs.repo }}/actions/workflows/${{ inputs.workflow_id }}/dispatches \
          -d '{"ref":"${{ inputs.ref }}","inputs":${{ inputs.inputs }}}'
      shell: bash
